#include "postquantiquecoin/wallet/Wallet.h"
#include "postquantiquecoin/core/Serialization.h"
#include "postquantiquecoin/crypto/Address.h"
#include "postquantiquecoin/crypto/Hashing.h"
#include "postquantiquecoin/crypto/SecureRandom.h"
#include <algorithm>
#include <chrono>
namespace pqc {
Wallet::Wallet(std::string n,std::filesystem::path p,PQCryptoProvider* c):name_(std::move(n)),storage_(std::move(p)),crypto_(c){}
std::vector<uint8_t> Wallet::DeriveKey(const std::string& password) const { std::vector<uint8_t> d(salt_); d.insert(d.end(),password.begin(),password.end()); for(int i=0;i<20000;++i){ auto h=Hashing::Sha3_256(d); d.assign(h.begin(),h.end()); d.insert(d.end(),salt_.begin(),salt_.end()); } d.resize(32); return d; }
std::vector<uint8_t> Wallet::Crypt(const std::vector<uint8_t>& in,const std::vector<uint8_t>& key,const std::vector<uint8_t>& nonce) const { std::vector<uint8_t> out=in; std::vector<uint8_t> stream=key; stream.insert(stream.end(),nonce.begin(),nonce.end()); size_t off=0; while(off<out.size()){ auto h=Hashing::Sha3_256(stream); for(size_t i=0;i<h.size()&&off<out.size();++i,++off) out[off]^=h[i]; stream.assign(h.begin(),h.end()); } return out; }
Result<Wallet> Wallet::CreateNew(const std::string& name,const std::string& password,const std::filesystem::path& path,PQCryptoProvider* crypto){ Wallet w(name,path,crypto); w.salt_=SecureRandom::Bytes(16); w.masterKey_=w.DeriveKey(password); w.locked_=false; auto a=w.GenerateNewAddress("default"); if(a.IsErr()) return Result<Wallet>::Err(a.Error()); auto s=w.Save(); if(s.IsErr()) return Result<Wallet>::Err(s.Error()); w.Lock(); return Result<Wallet>::Ok(std::move(w)); }
Result<void> Wallet::Load(){ if(!storage_.Exists()) return Result<void>::Err("wallet not found"); auto b=storage_.LoadEncryptedWallet(); if(b.IsErr()) return Result<void>::Err(b.Error()); if(b.Value().size()<4) return Result<void>::Err("wallet too small"); std::vector<uint8_t> body(b.Value().begin(),b.Value().end()-4); auto chk=Hashing::Sha3_256(body); if(!std::equal(b.Value().end()-4,b.Value().end(),chk.begin())) return Result<void>::Err("wallet checksum mismatch"); Deserializer d(body); auto magic=d.String(); if(magic.IsErr()||magic.Value()!="PQC_WALLET_V1") return Result<void>::Err("bad wallet format"); auto salt=d.Bytes(); if(salt.IsErr()) return Result<void>::Err(salt.Error()); salt_=salt.Value(); auto n=d.U64(); if(n.IsErr()) return Result<void>::Err(n.Error()); keys_.clear(); for(uint64_t i=0;i<n.Value();++i){ auto kb=d.Bytes(); if(kb.IsErr()) return Result<void>::Err(kb.Error()); auto k=WalletKey::Deserialize(kb.Value()); if(k.IsErr()) return Result<void>::Err(k.Error()); keys_.push_back(k.Value()); } locked_=true; masterKey_.clear(); return Result<void>::Ok(); }
Result<void> Wallet::Save(){ Serializer s; s.String("PQC_WALLET_V1"); s.Bytes(salt_); s.U64(keys_.size()); for(const auto& k:keys_) s.Bytes(k.Serialize()); auto body=s.Data(); auto chk=Hashing::Sha3_256(body); body.insert(body.end(),chk.begin(),chk.begin()+4); return storage_.SaveEncryptedWallet(body); }
Result<void> Wallet::Unlock(const std::string& password){ if(salt_.empty()){ auto l=Load(); if(l.IsErr()) return l; } auto k=DeriveKey(password); masterKey_=k; locked_=false; return Result<void>::Ok(); }
void Wallet::Lock(){ locked_=true; masterKey_.clear(); }
bool Wallet::IsLocked() const { return locked_; }
Result<std::vector<uint8_t>> Wallet::DecryptPrivate(const WalletKey& k) const { if(locked_) return Result<std::vector<uint8_t>>::Err("wallet locked"); if(k.encryptedPrivateKey.size()<12) return Result<std::vector<uint8_t>>::Err("bad encrypted key"); std::vector<uint8_t> nonce(k.encryptedPrivateKey.begin(),k.encryptedPrivateKey.begin()+12); std::vector<uint8_t> ct(k.encryptedPrivateKey.begin()+12,k.encryptedPrivateKey.end()); return Result<std::vector<uint8_t>>::Ok(Crypt(ct,masterKey_,nonce)); }
Result<std::string> Wallet::GenerateNewAddress(const std::string& label){ if(locked_) return Result<std::string>::Err("wallet locked"); auto kp=crypto_->GenerateSigningKeyPair(); auto nonce=SecureRandom::Bytes(12); auto enc=Crypt(kp.privateKey,masterKey_,nonce); nonce.insert(nonce.end(),enc.begin(),enc.end()); WalletKey wk; wk.label=label; wk.publicKey=kp.publicKey; wk.encryptedPrivateKey=nonce; wk.address=Address::FromPublicKey(kp.publicKey); wk.signatureAlgorithm=kp.algorithm; wk.createdTimestamp=static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); keys_.push_back(wk); return Result<std::string>::Ok(wk.address); }
std::vector<std::string> Wallet::ListAddresses() const { std::vector<std::string> v; for(const auto& k:keys_) v.push_back(k.address); return v; }
uint64_t Wallet::GetBalance(Blockchain& chain) const { uint64_t s=0; for(const auto& a:ListAddresses()) if(UINT64_MAX-s>=chain.GetBalance(a)) s+=chain.GetBalance(a); return s; }
Result<Transaction> Wallet::CreateTransaction(const std::string& to,uint64_t amount,uint64_t fee,Blockchain& chain){ if(locked_) return Result<Transaction>::Err("wallet locked"); for(const auto& k:keys_){ auto us=chain.GetSpendableUTXOs(k.address); uint64_t total=0; std::vector<UTXO> picked; for(const auto& u:us){ picked.push_back(u); total+=u.amountAtoms; if(total>=amount+fee) break; } if(total>=amount+fee){ Transaction tx; tx.timestamp=static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); for(const auto& u:picked) tx.inputs.push_back({u.txid,u.outputIndex,{},k.publicKey}); tx.outputs.push_back({amount,to,"PQC_PUBKEY_HASH"}); if(total>amount+fee) tx.outputs.push_back({total-amount-fee,k.address,"PQC_PUBKEY_HASH"}); auto stx=SignTransaction(tx); if(stx.IsErr()) return Result<Transaction>::Err(stx.Error()); return Result<Transaction>::Ok(tx); } } return Result<Transaction>::Err("insufficient funds"); }
Result<void> Wallet::SignTransaction(Transaction& tx){ if(locked_) return Result<void>::Err("wallet locked"); if(keys_.empty()) return Result<void>::Err("wallet has no keys"); auto pk=DecryptPrivate(keys_[0]); if(pk.IsErr()) return Result<void>::Err(pk.Error()); tx.Sign(*crypto_,pk.Value(),keys_[0].publicKey); return Result<void>::Ok(); }
Result<void> Wallet::ImportPrivateKey(const std::string& label,const std::vector<uint8_t>& pub,const std::vector<uint8_t>& priv){ if(locked_) return Result<void>::Err("wallet locked"); auto nonce=SecureRandom::Bytes(12); auto enc=Crypt(priv,masterKey_,nonce); nonce.insert(nonce.end(),enc.begin(),enc.end()); keys_.push_back({label,pub,nonce,Address::FromPublicKey(pub),"ML-DSA-65",0}); return Result<void>::Ok(); }
std::vector<std::vector<uint8_t>> Wallet::ExportPublicKeys() const { std::vector<std::vector<uint8_t>> v; for(const auto& k:keys_) v.push_back(k.publicKey); return v; }
Result<void> Wallet::Backup(const std::filesystem::path& p) const { auto r=storage_.Backup(p); return r.IsOk()?Result<void>::Ok():Result<void>::Err(r.Error()); }
Result<void> Wallet::Rescan(Blockchain& chain){ (void)chain; return Result<void>::Ok(); }
const std::string& Wallet::Name() const { return name_; }
}
