#include "postquantiquecoin/wallet/WalletRecoveryFile.h"
#include "postquantiquecoin/core/Serialization.h"
#include "postquantiquecoin/crypto/Hashing.h"
#include <algorithm>
namespace pqc {
namespace {
std::array<uint8_t,32> ChecksumPub(const WalletRecoveryPublicFile& f){ std::vector<uint8_t> d{'P','Q','C','R','E','C','O','V','E','R','Y','P','U','B'}; d.push_back(f.networkId); d.insert(d.end(),f.kemAlgorithm.begin(),f.kemAlgorithm.end()); d.insert(d.end(),f.kemPublicKey.begin(),f.kemPublicKey.end()); d.insert(d.end(),f.walletFingerprint.begin(),f.walletFingerprint.end()); return Hashing::Sha3_256(d); }
std::array<uint8_t,32> ChecksumSec(const WalletRecoverySecretFile& f){ std::vector<uint8_t> d{'P','Q','C','R','E','C','O','V','E','R','Y','S','E','C','R','E','T'}; d.insert(d.end(),f.kemAlgorithm.begin(),f.kemAlgorithm.end()); d.insert(d.end(),f.encryptedKemPrivateKey.begin(),f.encryptedKemPrivateKey.end()); d.insert(d.end(),f.salt.begin(),f.salt.end()); d.insert(d.end(),f.nonce.begin(),f.nonce.end()); d.insert(d.end(),f.tag.begin(),f.tag.end()); return Hashing::Sha3_256(d); }
Result<std::array<uint8_t,32>> Read32(Deserializer& d,const char* field){ std::array<uint8_t,32> out{}; auto b=d.Bytes(); if(b.IsErr()) return Result<std::array<uint8_t,32>>::Err(b.Error()); if(b.Value().size()!=32) return Result<std::array<uint8_t,32>>::Err(std::string("bad ")+field+" length"); std::copy(b.Value().begin(),b.Value().end(),out.begin()); return Result<std::array<uint8_t,32>>::Ok(out); }
}
std::vector<uint8_t> WalletRecoveryPublicFile::Serialize() const{ auto f=*this; f.checksum=ChecksumPub(f); Serializer s; s.String("PQCRECOVERYPUB"); s.U32(f.version); s.U32(f.networkId); s.String(f.kemAlgorithm); s.Bytes(f.kemPublicKey); s.Bytes(std::vector<uint8_t>(f.walletFingerprint.begin(),f.walletFingerprint.end())); s.Bytes(std::vector<uint8_t>(f.checksum.begin(),f.checksum.end())); return s.Data(); }
Result<WalletRecoveryPublicFile> WalletRecoveryPublicFile::Deserialize(const std::vector<uint8_t>& data){ Deserializer d(data); WalletRecoveryPublicFile f; auto m=d.String(); if(m.IsErr()) return Result<WalletRecoveryPublicFile>::Err(m.Error()); if(m.Value()!="PQCRECOVERYPUB") return Result<WalletRecoveryPublicFile>::Err("bad public recovery magic"); auto v=d.U32(); if(v.IsErr()) return Result<WalletRecoveryPublicFile>::Err(v.Error()); f.version=v.Value(); auto n=d.U32(); if(n.IsErr()) return Result<WalletRecoveryPublicFile>::Err(n.Error()); f.networkId=static_cast<uint8_t>(n.Value()); auto alg=d.String(); if(alg.IsErr()) return Result<WalletRecoveryPublicFile>::Err(alg.Error()); f.kemAlgorithm=alg.Value(); auto pk=d.Bytes(); if(pk.IsErr()) return Result<WalletRecoveryPublicFile>::Err(pk.Error()); f.kemPublicKey=pk.Value(); auto fp=Read32(d,"wallet fingerprint"); if(fp.IsErr()) return Result<WalletRecoveryPublicFile>::Err(fp.Error()); f.walletFingerprint=fp.Value(); auto chk=Read32(d,"checksum"); if(chk.IsErr()) return Result<WalletRecoveryPublicFile>::Err(chk.Error()); f.checksum=chk.Value(); if(!d.End()) return Result<WalletRecoveryPublicFile>::Err("trailing public recovery bytes"); if(ChecksumPub(f)!=f.checksum) return Result<WalletRecoveryPublicFile>::Err("public recovery checksum mismatch"); return Result<WalletRecoveryPublicFile>::Ok(f); }
std::vector<uint8_t> WalletRecoverySecretFile::Serialize() const{ auto f=*this; f.checksum=ChecksumSec(f); Serializer s; s.String("PQCRECOVERYSECRET"); s.U32(f.version); s.String(f.kemAlgorithm); s.Bytes(f.encryptedKemPrivateKey); s.Bytes(f.salt); s.Bytes(f.nonce); s.Bytes(f.tag); s.Bytes(std::vector<uint8_t>(f.checksum.begin(),f.checksum.end())); return s.Data(); }
Result<WalletRecoverySecretFile> WalletRecoverySecretFile::Deserialize(const std::vector<uint8_t>& data){ Deserializer d(data); WalletRecoverySecretFile f; auto m=d.String(); if(m.IsErr()) return Result<WalletRecoverySecretFile>::Err(m.Error()); if(m.Value()!="PQCRECOVERYSECRET") return Result<WalletRecoverySecretFile>::Err("bad secret recovery magic"); auto v=d.U32(); if(v.IsErr()) return Result<WalletRecoverySecretFile>::Err(v.Error()); f.version=v.Value(); auto alg=d.String(); if(alg.IsErr()) return Result<WalletRecoverySecretFile>::Err(alg.Error()); f.kemAlgorithm=alg.Value(); auto enc=d.Bytes(); if(enc.IsErr()) return Result<WalletRecoverySecretFile>::Err(enc.Error()); f.encryptedKemPrivateKey=enc.Value(); auto salt=d.Bytes(); if(salt.IsErr()) return Result<WalletRecoverySecretFile>::Err(salt.Error()); f.salt=salt.Value(); auto nonce=d.Bytes(); if(nonce.IsErr()) return Result<WalletRecoverySecretFile>::Err(nonce.Error()); f.nonce=nonce.Value(); auto tag=d.Bytes(); if(tag.IsErr()) return Result<WalletRecoverySecretFile>::Err(tag.Error()); f.tag=tag.Value(); auto chk=Read32(d,"checksum"); if(chk.IsErr()) return Result<WalletRecoverySecretFile>::Err(chk.Error()); f.checksum=chk.Value(); if(!d.End()) return Result<WalletRecoverySecretFile>::Err("trailing secret recovery bytes"); if(ChecksumSec(f)!=f.checksum) return Result<WalletRecoverySecretFile>::Err("secret recovery checksum mismatch"); return Result<WalletRecoverySecretFile>::Ok(f); }
}
