#include "postquantiquecoin/wallet/WalletKey.h"
#include "postquantiquecoin/core/Serialization.h"
#include <algorithm>
namespace pqc {
std::vector<uint8_t> WalletKey::Serialize() const {
    Serializer s; s.U32(2); s.String(label); s.String(address); s.String(signatureAlgorithm); s.String(kemAlgorithm); s.Bytes(EffectivePublicKey()); s.Bytes(kemPublicKey); s.Bytes(EffectiveEncryptedRecord()); s.Bytes(std::vector<uint8_t>(keyFingerprint.begin(),keyFingerprint.end())); s.U64(createdTimestamp); return s.Data();
}
Result<WalletKey> WalletKey::Deserialize(const std::vector<uint8_t>& data){
    Deserializer d(data); WalletKey k; auto v=d.U32(); if(v.IsErr()) return Result<WalletKey>::Err(v.Error());
    if(v.Value()==1){ auto l=d.String(); if(l.IsErr()) return Result<WalletKey>::Err(l.Error()); k.label=l.Value(); auto p=d.Bytes(); if(p.IsErr()) return Result<WalletKey>::Err(p.Error()); k.publicKey=p.Value(); k.signingPublicKey=k.publicKey; auto e=d.Bytes(); if(e.IsErr()) return Result<WalletKey>::Err(e.Error()); k.encryptedPrivateKey=e.Value(); k.encryptedPrivateKeyRecord=k.encryptedPrivateKey; auto a=d.String(); if(a.IsErr()) return Result<WalletKey>::Err(a.Error()); k.address=a.Value(); auto alg=d.String(); if(alg.IsErr()) return Result<WalletKey>::Err(alg.Error()); k.signatureAlgorithm=alg.Value(); auto ts=d.U64(); if(ts.IsErr()) return Result<WalletKey>::Err(ts.Error()); k.createdTimestamp=ts.Value(); return Result<WalletKey>::Ok(k); }
    if(v.Value()!=2) return Result<WalletKey>::Err("bad wallet key version");
    auto l=d.String(); if(l.IsErr()) return Result<WalletKey>::Err(l.Error()); k.label=l.Value(); auto a=d.String(); if(a.IsErr()) return Result<WalletKey>::Err(a.Error()); k.address=a.Value(); auto sig=d.String(); if(sig.IsErr()) return Result<WalletKey>::Err(sig.Error()); k.signatureAlgorithm=sig.Value(); auto kem=d.String(); if(kem.IsErr()) return Result<WalletKey>::Err(kem.Error()); k.kemAlgorithm=kem.Value(); auto spk=d.Bytes(); if(spk.IsErr()) return Result<WalletKey>::Err(spk.Error()); k.signingPublicKey=spk.Value(); k.publicKey=k.signingPublicKey; auto kpk=d.Bytes(); if(kpk.IsErr()) return Result<WalletKey>::Err(kpk.Error()); k.kemPublicKey=kpk.Value(); auto rec=d.Bytes(); if(rec.IsErr()) return Result<WalletKey>::Err(rec.Error()); k.encryptedPrivateKeyRecord=rec.Value(); k.encryptedPrivateKey=k.encryptedPrivateKeyRecord; auto fp=d.Bytes(); if(fp.IsErr()) return Result<WalletKey>::Err(fp.Error()); if(fp.Value().size()!=32) return Result<WalletKey>::Err("bad key fingerprint length"); std::copy(fp.Value().begin(),fp.Value().end(),k.keyFingerprint.begin()); auto ts=d.U64(); if(ts.IsErr()) return Result<WalletKey>::Err(ts.Error()); k.createdTimestamp=ts.Value(); if(!d.End()) return Result<WalletKey>::Err("trailing wallet key bytes"); return Result<WalletKey>::Ok(k);
}
}
