#include "postquantiquecoin/wallet/Wallet.h"
#include "postquantiquecoin/core/Serialization.h"
#include "postquantiquecoin/crypto/PQCAddress.h"
#include "postquantiquecoin/crypto/PQPrivateKeyRecord.h"
#include "postquantiquecoin/crypto/Hashing.h"
#include "postquantiquecoin/crypto/SecureRandom.h"
#include "postquantiquecoin/wallet/WalletDatFormat.h"
#include "postquantiquecoin/wallet/WalletEncryption.h"
#include "postquantiquecoin/wallet/WalletSecretBox.h"
#include <algorithm>
#include <chrono>
namespace pqc {
namespace { uint64_t Now(){ return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); } std::vector<uint8_t> MasterKeyFromPassword(const std::string& password){ std::vector<uint8_t> d{'P','Q','C','_','W','A','L','L','E','T','_','M','A','S','T','E','R','_','V','2'}; d.insert(d.end(),password.begin(),password.end()); auto h=pqc::Hashing::Sha3_256(d); return std::vector<uint8_t>(h.begin(),h.end()); } std::vector<uint8_t> KeyNonceAd(const WalletKey& k){ std::vector<uint8_t> aad{'P','Q','C','_','W','A','L','L','E','T','_','K','E','Y'}; aad.insert(aad.end(),k.address.begin(),k.address.end()); return aad; } }
Wallet::Wallet(std::string n,std::filesystem::path p,PQCryptoProvider* c):name_(std::move(n)),storage_(std::move(p)),crypto_(c){}
Result<Wallet> Wallet::CreateNew(const std::string& name,const std::string& password,const std::filesystem::path& path,PQCryptoProvider* crypto){ Wallet w(name,path,crypto); w.locked_=false; w.unlockPassword_=password; w.masterKey_=SecureBuffer(MasterKeyFromPassword(password)); w.unlockedUntil=Now()+w.autoLockSeconds; auto a=w.GenerateNewAddress("default"); if(a.IsErr()) return Result<Wallet>::Err(a.Error()); auto s=w.EncryptAndStorePlaintext(password); if(s.IsErr()) return Result<Wallet>::Err(s.Error()); w.Lock(); return Result<Wallet>::Ok(std::move(w)); }
std::vector<uint8_t> Wallet::SerializePlaintext() const { Serializer s; s.String("PQC_WALLET_KEYS_V2"); s.U64(keys_.size()); for(const auto& k:keys_) s.Bytes(k.Serialize()); return s.Data(); }
Result<void> Wallet::DeserializePlaintext(const std::vector<uint8_t>& plaintext){ Deserializer d(plaintext); auto magic=d.String(); if(magic.IsErr()) return Result<void>::Err(magic.Error()); if(magic.Value()!="PQC_WALLET_KEYS_V2") return Result<void>::Err("bad wallet plaintext magic"); auto n=d.U64(); if(n.IsErr()) return Result<void>::Err(n.Error()); keys_.clear(); for(uint64_t i=0;i<n.Value();++i){ auto kb=d.Bytes(); if(kb.IsErr()) return Result<void>::Err(kb.Error()); auto k=WalletKey::Deserialize(kb.Value()); if(k.IsErr()) return Result<void>::Err(k.Error()); keys_.push_back(k.Value()); } if(!d.End()) return Result<void>::Err("trailing wallet plaintext bytes"); return Result<void>::Ok(); }
Result<void> Wallet::EncryptAndStorePlaintext(const std::string& password){ auto blob=WalletEncryption::EncryptPayload(SerializePlaintext(),password); if(blob.ciphertext.empty() && !SerializePlaintext().empty()) return Result<void>::Err("wallet encryption failed"); return storage_.SaveEncryptedWallet(WalletDatFormat::Serialize(blob)); }
Result<void> Wallet::Load(){ if(!storage_.Exists()) return Result<void>::Err("wallet not found"); auto b=storage_.LoadEncryptedWallet(); if(b.IsErr()) return Result<void>::Err(b.Error()); auto blob=WalletDatFormat::Deserialize(b.Value()); if(blob.IsErr()) return Result<void>::Err(blob.Error()); locked_=true; masterKey_.Wipe(); unlockPassword_.clear(); keys_.clear(); return Result<void>::Ok(); }
Result<void> Wallet::Save(){ if(locked_) return Result<void>::Err("wallet locked"); if(unlockPassword_.empty()) return Result<void>::Err("wallet save requires unlocked password context"); return EncryptAndStorePlaintext(unlockPassword_); }
Result<void> Wallet::Unlock(const std::string& password){ return Unlock(password, autoLockSeconds); }
Result<void> Wallet::Unlock(const std::string& password,uint64_t timeoutSeconds){ auto b=storage_.LoadEncryptedWallet(); if(b.IsErr()) return Result<void>::Err(b.Error()); auto blob=WalletDatFormat::Deserialize(b.Value()); if(blob.IsErr()) return Result<void>::Err(blob.Error()); auto pt=WalletEncryption::DecryptPayload(blob.Value(),password); if(pt.IsErr()) return Result<void>::Err(pt.Error()); auto dp=DeserializePlaintext(pt.Value()); if(dp.IsErr()) return dp; masterKey_=SecureBuffer(MasterKeyFromPassword(password)); unlockPassword_=password; locked_=false; unlockedUntil=Now()+timeoutSeconds; return Result<void>::Ok(); }
void Wallet::Lock(){ locked_=true; masterKey_.Wipe(); unlockPassword_.clear(); unlockedUntil=0; }
bool Wallet::IsLocked() const { return locked_; }
void Wallet::MaybeAutoLock(){ if(!locked_ && unlockedUntil!=0 && Now()>=unlockedUntil) Lock(); }
void Wallet::SetAutoLockTimeout(uint64_t seconds){ autoLockSeconds=seconds; if(!locked_) unlockedUntil=Now()+seconds; }
Result<std::vector<uint8_t>> Wallet::DecryptPrivate(const WalletKey& k) const { if(locked_) return Result<std::vector<uint8_t>>::Err("wallet locked"); const auto& record=k.EffectiveEncryptedRecord(); if(record.size()<44) return Result<std::vector<uint8_t>>::Err("bad encrypted key record"); std::vector<uint8_t> nonce(record.begin(),record.begin()+12); std::vector<uint8_t> tag(record.begin()+12,record.begin()+44); std::vector<uint8_t> ct(record.begin()+44,record.end()); auto key=masterKey_.ToVectorCopy(); auto pt=WalletSecretBox::Decrypt(key,nonce,ct,KeyNonceAd(k),tag); if(pt.IsErr()) return Result<std::vector<uint8_t>>::Err(pt.Error()); auto rec=PQPrivateKeyRecord::Deserialize(pt.Value()); if(rec.IsErr()) return Result<std::vector<uint8_t>>::Err(rec.Error()); return Result<std::vector<uint8_t>>::Ok(rec.Value().signingPrivateKey); }
Result<std::string> Wallet::GenerateNewAddress(const std::string& label){ MaybeAutoLock(); if(locked_) return Result<std::string>::Err("wallet locked"); auto kp=crypto_->GenerateSigningKeyPair(); auto kem=crypto_->GenerateKemKeyPair(); PQPrivateKeyRecord rec; rec.signatureAlgorithm=kp.algorithm; rec.kemAlgorithm=kem.algorithm; rec.signingPrivateKey=kp.privateKey; rec.signingPublicKey=kp.publicKey; rec.kemPrivateKey=kem.privateKey; rec.kemPublicKey=kem.publicKey; rec.createdTimestamp=Now(); rec.keyFingerprint=rec.ComputeFingerprint(); WalletKey wk; wk.label=label; wk.address=PQCAddress::FromPublicKey(kp.publicKey); wk.signatureAlgorithm=kp.algorithm; wk.kemAlgorithm=kem.algorithm; wk.signingPublicKey=kp.publicKey; wk.publicKey=kp.publicKey; wk.kemPublicKey=kem.publicKey; wk.keyFingerprint=rec.keyFingerprint; wk.createdTimestamp=rec.createdTimestamp; auto nonce=SecureRandom::Bytes(12); auto enc=WalletSecretBox::Encrypt(masterKey_.ToVectorCopy(),nonce,rec.Serialize(),KeyNonceAd(wk)); wk.encryptedPrivateKeyRecord=nonce; wk.encryptedPrivateKeyRecord.insert(wk.encryptedPrivateKeyRecord.end(),enc.tag.begin(),enc.tag.end()); wk.encryptedPrivateKeyRecord.insert(wk.encryptedPrivateKeyRecord.end(),enc.ciphertext.begin(),enc.ciphertext.end()); wk.encryptedPrivateKey=wk.encryptedPrivateKeyRecord; keys_.push_back(wk); return Result<std::string>::Ok(wk.address); }
std::vector<std::string> Wallet::ListAddresses() const { std::vector<std::string> v; for(const auto& k:keys_) v.push_back(k.address); return v; }
uint64_t Wallet::GetBalance(Blockchain& chain) const { return GetAvailableBalance(chain); }
uint64_t Wallet::GetConfirmedBalance(Blockchain& chain) const { uint64_t s=0; for(const auto& a:ListAddresses()) if(UINT64_MAX-s>=chain.GetBalance(a)) s+=chain.GetBalance(a); return s; }
uint64_t Wallet::GetImmatureBalance(Blockchain&) const { return 0; } uint64_t Wallet::GetPendingIncomingBalance(Blockchain&) const { return 0; } uint64_t Wallet::GetPendingOutgoingBalance(Blockchain&) const { return 0; } uint64_t Wallet::GetAvailableBalance(Blockchain& chain) const { return GetConfirmedBalance(chain); } uint64_t Wallet::GetTotalBalance(Blockchain& chain) const { return GetConfirmedBalance(chain); }
Result<Transaction> Wallet::CreateTransaction(const std::string& to,uint64_t amount,uint64_t fee,Blockchain& chain){ MaybeAutoLock(); if(locked_) return Result<Transaction>::Err("wallet locked"); auto toDecoded=PQCAddress::Decode(to); if(toDecoded.IsErr()) return Result<Transaction>::Err(toDecoded.Error()); for(const auto& k:keys_){ auto us=chain.GetSpendableUTXOs(k.address); uint64_t total=0; std::vector<UTXO> picked; for(const auto& u:us){ picked.push_back(u); total+=u.amountAtoms; if(total>=amount+fee) break; } if(total>=amount+fee){ Transaction tx; tx.timestamp=Now(); tx.signatureAlgorithm=k.signatureAlgorithm; for(const auto& u:picked){ TxInput in; in.previousTxid=u.txid; in.outputIndex=u.outputIndex; in.publicKey=k.EffectivePublicKey(); in.signatureAlgorithm=k.signatureAlgorithm; tx.inputs.push_back(in); } TxOutput out; out.amountAtoms=amount; out.address=to; out.requiredSignatureAlgorithm=k.signatureAlgorithm; out.publicKeyHash=toDecoded.Value().publicKeyHash; tx.outputs.push_back(out); if(total>amount+fee){ auto cd=PQCAddress::Decode(k.address); TxOutput change; change.amountAtoms=total-amount-fee; change.address=k.address; change.requiredSignatureAlgorithm=k.signatureAlgorithm; if(cd.IsOk()) change.publicKeyHash=cd.Value().publicKeyHash; tx.outputs.push_back(change); } auto pk=DecryptPrivate(k); if(pk.IsErr()) return Result<Transaction>::Err(pk.Error()); for(size_t i=0;i<tx.inputs.size();++i){ TxOutput ref; ref.address=k.address; ref.requiredSignatureAlgorithm=k.signatureAlgorithm; ref.publicKeyHash=PQCAddress::HashPublicKey(k.EffectivePublicKey()); auto si=tx.SignInput(i,ref,*crypto_,pk.Value(),k.EffectivePublicKey()); if(si.IsErr()) return Result<Transaction>::Err(si.Error()); } return Result<Transaction>::Ok(tx); } } return Result<Transaction>::Err("insufficient funds"); }
Result<void> Wallet::SignTransaction(Transaction& tx){ MaybeAutoLock(); if(locked_) return Result<void>::Err("wallet locked"); for(size_t i=0;i<tx.inputs.size();++i){ bool signedInput=false; for(const auto& k:keys_){ if(tx.inputs[i].publicKey.empty() || tx.inputs[i].publicKey==k.EffectivePublicKey()){ auto pk=DecryptPrivate(k); if(pk.IsErr()) return Result<void>::Err(pk.Error()); TxOutput ref; ref.address=k.address; ref.requiredSignatureAlgorithm=k.signatureAlgorithm; ref.publicKeyHash=PQCAddress::HashPublicKey(k.EffectivePublicKey()); auto r=tx.SignInput(i,ref,*crypto_,pk.Value(),k.EffectivePublicKey()); if(r.IsErr()) return r; signedInput=true; break; } } if(!signedInput && !keys_.empty()){ const auto& k=keys_.front(); auto pk=DecryptPrivate(k); if(pk.IsErr()) return Result<void>::Err(pk.Error()); TxOutput ref; ref.address=k.address; ref.requiredSignatureAlgorithm=k.signatureAlgorithm; ref.publicKeyHash=PQCAddress::HashPublicKey(k.EffectivePublicKey()); auto r=tx.SignInput(i,ref,*crypto_,pk.Value(),k.EffectivePublicKey()); if(r.IsErr()) return r; signedInput=true; } if(!signedInput) return Result<void>::Err("no wallet key for input"); } return Result<void>::Ok(); }
Result<void> Wallet::ImportPrivateKey(const std::string& label,const std::vector<uint8_t>& pub,const std::vector<uint8_t>& priv){ MaybeAutoLock(); if(locked_) return Result<void>::Err("wallet locked"); PQPrivateKeyRecord rec; rec.signingPrivateKey=priv; rec.signingPublicKey=pub; rec.createdTimestamp=Now(); rec.keyFingerprint=rec.ComputeFingerprint(); WalletKey wk; wk.label=label; wk.address=PQCAddress::FromPublicKey(pub); wk.signingPublicKey=pub; wk.publicKey=pub; wk.keyFingerprint=rec.keyFingerprint; wk.createdTimestamp=rec.createdTimestamp; auto nonce=SecureRandom::Bytes(12); auto enc=WalletSecretBox::Encrypt(masterKey_.ToVectorCopy(),nonce,rec.Serialize(),KeyNonceAd(wk)); wk.encryptedPrivateKeyRecord=nonce; wk.encryptedPrivateKeyRecord.insert(wk.encryptedPrivateKeyRecord.end(),enc.tag.begin(),enc.tag.end()); wk.encryptedPrivateKeyRecord.insert(wk.encryptedPrivateKeyRecord.end(),enc.ciphertext.begin(),enc.ciphertext.end()); wk.encryptedPrivateKey=wk.encryptedPrivateKeyRecord; keys_.push_back(wk); return Result<void>::Ok(); }
std::vector<std::vector<uint8_t>> Wallet::ExportPublicKeys() const { std::vector<std::vector<uint8_t>> v; for(const auto& k:keys_) v.push_back(k.EffectivePublicKey()); return v; }
Result<void> Wallet::Backup(const std::filesystem::path& p) const { auto r=storage_.Backup(p); return r.IsOk()?Result<void>::Ok():Result<void>::Err(r.Error()); }
Result<void> Wallet::Rescan(Blockchain& chain){ (void)chain; return Result<void>::Ok(); }
const std::string& Wallet::Name() const { return name_; }
}
