#include "postquantiquecoin/blockchain/Block.h"
#include "postquantiquecoin/blockchain/MerkleTree.h"
#include "postquantiquecoin/core/Constants.h"
#include "postquantiquecoin/core/Serialization.h"
namespace pqc {
std::string Block::GetHash() const { return header.GetHash(); }
std::vector<uint8_t> Block::Serialize() const { Serializer s; auto hs=header.Serialize(); s.Bytes(hs); s.U64(transactions.size()); for(const auto& tx:transactions) s.Bytes(tx.Serialize(true)); return s.Data(); }
Result<Block> Block::Deserialize(const std::vector<uint8_t>& data){ Deserializer d(data); Block b; auto hb=d.Bytes(); if(hb.IsErr()) return Result<Block>::Err(hb.Error()); Deserializer hd(hb.Value()); auto domain=hd.String(); if(domain.IsErr()) return Result<Block>::Err(domain.Error()); auto ver=hd.U32(); if(ver.IsErr()) return Result<Block>::Err(ver.Error()); b.header.version=ver.Value(); auto cv=hd.U32(); if(cv.IsErr()) return Result<Block>::Err(cv.Error()); b.header.consensusVersion=static_cast<uint16_t>(cv.Value()); auto pai=hd.U32(); if(pai.IsErr()) return Result<Block>::Err(pai.Error()); b.header.powAlgorithmId=static_cast<uint16_t>(pai.Value()); auto prev=hd.String(); if(prev.IsErr()) return Result<Block>::Err(prev.Error()); b.header.previousHash=prev.Value(); auto mr=hd.String(); if(mr.IsErr()) return Result<Block>::Err(mr.Error()); b.header.merkleRoot=mr.Value(); auto ts=hd.U64(); if(ts.IsErr()) return Result<Block>::Err(ts.Error()); b.header.timestamp=ts.Value(); auto bits=hd.U32(); if(bits.IsErr()) return Result<Block>::Err(bits.Error()); b.header.bits=bits.Value(); auto nonce=hd.U64(); if(nonce.IsErr()) return Result<Block>::Err(nonce.Error()); b.header.nonce=nonce.Value(); auto height=hd.U64(); if(height.IsErr()) return Result<Block>::Err(height.Error()); b.header.height=height.Value(); auto n=d.U64(); if(n.IsErr()) return Result<Block>::Err(n.Error()); if(n.Value()>100000) return Result<Block>::Err("too many transactions"); for(uint64_t i=0;i<n.Value();++i){ auto tb=d.Bytes(); if(tb.IsErr()) return Result<Block>::Err(tb.Error()); auto tx=Transaction::Deserialize(tb.Value()); if(tx.IsErr()) return Result<Block>::Err(tx.Error()); b.transactions.push_back(tx.Value()); } if(!d.End()) return Result<Block>::Err("trailing block bytes"); return Result<Block>::Ok(b); }
Result<void> Block::ValidateBasic() const { if(transactions.empty()) return Result<void>::Err("block without transactions"); if(Serialize().size()>constants::MAX_BLOCK_BYTES) return Result<void>::Err("block too large"); if(!transactions[0].IsCoinbase()) return Result<void>::Err("first transaction is not coinbase"); for(size_t i=1;i<transactions.size();++i) if(transactions[i].IsCoinbase()) return Result<void>::Err("extra coinbase"); for(const auto& tx:transactions){ auto r=tx.ValidateBasic(); if(r.IsErr() && !tx.IsCoinbase()) return r; } if(header.merkleRoot!=MerkleTree::ComputeRoot(transactions)) return Result<void>::Err("bad merkle root"); return Result<void>::Ok(); }
}
