#include "postquantiquecoin/blockchain/Blockchain.h"
#include "postquantiquecoin/blockchain/ChainValidation.h"
#include "postquantiquecoin/blockchain/Consensus.h"
#include "postquantiquecoin/blockchain/Genesis.h"
#include "postquantiquecoin/blockchain/MerkleTree.h"
#include "postquantiquecoin/storage/UtxoStorage.h"
#include <algorithm>
namespace pqc {
Blockchain::Blockchain(std::filesystem::path d,ChainParams p,PQCryptoProvider* c):dataDir_(std::move(d)),params_(std::move(p)),crypto_(c),files_(dataDir_),index_(dataDir_/"chainstate"/"block_index.dat"){}
Result<Blockchain> Blockchain::OpenOrCreate(const std::filesystem::path& d,const ChainParams& p,PQCryptoProvider* c){ Blockchain bc(d,p,c); auto r=bc.Initialize(); if(r.IsErr()) return Result<Blockchain>::Err(r.Error()); return Result<Blockchain>::Ok(std::move(bc)); }
Result<void> Blockchain::Initialize(){ auto e=files_.EnsureDataDirectories(); if(e.IsErr()) return e; auto l=Load(); if(l.IsErr()) return l; if(chain_.empty()){ Block g=Genesis::BuildGenesisBlock(params_); auto s=StoreBlock(g); if(s.IsErr()) return s; chain_.push_back(g); index_.Add({g.GetHash(),g.header.previousHash,0,g.header.bits,g.header.timestamp,0,0,g.Serialize().size(),"0"}); auto c=ConnectBlock(g); if(c.IsErr()) return c; return Save(); } return Result<void>::Ok(); }
std::filesystem::path Blockchain::BlockPath(uint64_t h) const { return dataDir_/"blocks"/(std::to_string(h)+".blk"); }
Result<void> Blockchain::StoreBlock(const Block& b){ return FileStorage::AtomicWrite(BlockPath(b.header.height), b.Serialize()); }
Result<void> Blockchain::Load(){ chain_.clear(); index_.Load(); for(uint64_t h=0;;++h){ auto p=BlockPath(h); if(!FileStorage::FileExists(p)) break; auto bytes=FileStorage::ReadFile(p); if(bytes.IsErr()) return Result<void>::Err(bytes.Error()); auto b=Block::Deserialize(bytes.Value()); if(b.IsErr()) return Result<void>::Err(b.Error()); chain_.push_back(b.Value()); } auto r=RebuildUTXO(); if(r.IsErr()) return r; return Result<void>::Ok(); }
Result<void> Blockchain::Save(){ auto ir=index_.Save(); if(ir.IsErr()) return ir; UtxoStorage us(dataDir_/"chainstate"/"utxos.dat"); return us.SaveSnapshot(utxos_); }
Result<void> Blockchain::ValidateBlock(const Block& block) const { auto basic=block.ValidateBasic(); if(basic.IsErr()) return basic; if(chain_.empty()){ if(block.header.height!=0) return Result<void>::Err("bad genesis height"); } else { if(block.header.previousHash!=GetTipHash()) return Result<void>::Err("invalid previous hash"); if(block.header.height!=GetHeight()+1) return Result<void>::Err("invalid block height"); } if(block.header.merkleRoot!=MerkleTree::ComputeRoot(block.transactions)) return Result<void>::Err("invalid merkle root"); auto fees=ChainValidation::CalculateFees(block,utxos_,block.header.height,params_.coinbaseMaturity); if(fees.IsErr()) return Result<void>::Err(fees.Error()); return Consensus::ValidateBlock(block,params_,mintedSupply_,fees.Value(),crypto_); }
Result<void> Blockchain::ConnectBlock(const Block& block){ UTXOSet copy=utxos_; uint64_t fees=0; auto fr=ChainValidation::CalculateFees(block,copy,block.header.height,params_.coinbaseMaturity); if(fr.IsOk()) fees=fr.Value(); (void)fees; for(size_t i=0;i<block.transactions.size();++i){ auto r=copy.ApplyTransaction(block.transactions[i],block.header.height,i==0,block.header.height,params_.coinbaseMaturity); if(r.IsErr()) return Result<void>::Err(r.Error()); } uint64_t coinbase=ChainValidation::CoinbaseOutputSum(block); uint64_t subsidy=params_.GetBlockSubsidy(block.header.height,mintedSupply_); uint64_t minted=std::min(coinbase,subsidy); if(mintedSupply_>params_.maxSupplyAtoms || minted>params_.maxSupplyAtoms-mintedSupply_) return Result<void>::Err("max supply exceeded"); utxos_=std::move(copy); mintedSupply_+=minted; return Result<void>::Ok(); }
Result<void> Blockchain::AddBlock(const Block& block){ auto v=ValidateBlock(block); if(v.IsErr()) return v; auto c=ConnectBlock(block); if(c.IsErr()) return c; auto s=StoreBlock(block); if(s.IsErr()) return s; chain_.push_back(block); auto hash=block.GetHash(); auto a=index_.Add({hash,block.header.previousHash,block.header.height,block.header.bits,block.header.timestamp,0,0,block.Serialize().size(),std::to_string(block.header.height)}); if(a.IsErr()) return a; mempool_.RemoveConfirmedTransactions(block); return Save(); }
Result<void> Blockchain::DisconnectTip(){ if(chain_.size()<=1) return Result<void>::Err("cannot disconnect genesis"); chain_.pop_back(); return RebuildUTXO(); }
Result<void> Blockchain::RebuildUTXO(){ utxos_.Clear(); mintedSupply_=0; for(const auto& b:chain_){ auto c=ConnectBlock(b); if(c.IsErr()) return c; } return Result<void>::Ok(); }
Result<void> Blockchain::ValidateChain() const { UTXOSet view; uint64_t minted=0; std::string prev; for(size_t i=0;i<chain_.size();++i){ const auto& b=chain_[i]; if(b.header.height!=i) return Result<void>::Err("chain height mismatch"); if(i>0 && b.header.previousHash!=prev) return Result<void>::Err("chain link mismatch"); auto fees=ChainValidation::CalculateFees(b,view,b.header.height,params_.coinbaseMaturity); if(fees.IsErr()) return Result<void>::Err(fees.Error()); auto cv=Consensus::ValidateBlock(b,params_,minted,fees.Value(),crypto_); if(cv.IsErr()) return cv; for(size_t t=0;t<b.transactions.size();++t){ auto ar=view.ApplyTransaction(b.transactions[t],b.header.height,t==0,b.header.height,params_.coinbaseMaturity); if(ar.IsErr()) return Result<void>::Err(ar.Error()); } uint64_t subsidy=params_.GetBlockSubsidy(b.header.height,minted); uint64_t coinbase=ChainValidation::CoinbaseOutputSum(b); minted+=std::min(subsidy,coinbase); prev=b.GetHash(); } return Result<void>::Ok(); }
Result<void> Blockchain::AddTransactionToMempool(const Transaction& tx){ return mempool_.AddTransaction(tx,utxos_,GetHeight(),params_,crypto_); }
std::optional<Block> Blockchain::GetBlockByHash(const std::string& h) const { for(const auto& b:chain_) if(b.GetHash()==h) return b; return std::nullopt; }
std::optional<Block> Blockchain::GetBlockByHeight(uint64_t h) const { if(h>=chain_.size()) return std::nullopt; return chain_[static_cast<size_t>(h)]; }
std::string Blockchain::GetTipHash() const { return chain_.empty()?std::string(64,'0'):chain_.back().GetHash(); }
uint64_t Blockchain::GetHeight() const { return chain_.empty()?0:chain_.back().header.height; }
uint64_t Blockchain::GetBalance(const std::string& a) const { return utxos_.GetBalance(a,GetHeight(),params_.coinbaseMaturity); }
std::vector<UTXO> Blockchain::GetSpendableUTXOs(const std::string& a) const { return utxos_.GetSpendableUTXOs(a,GetHeight(),params_.coinbaseMaturity); }
Mempool& Blockchain::GetMempool(){ return mempool_; }
const UTXOSet& Blockchain::GetUTXOSet() const { return utxos_; }
uint64_t Blockchain::GetMintedSupply() const { return mintedSupply_; }
uint64_t Blockchain::GetNextSubsidy() const { return params_.GetBlockSubsidy(GetHeight()+1,mintedSupply_); }
const ChainParams& Blockchain::Params() const { return params_; }
}
