#include "postquantiquecoin/blockchain/Consensus.h"
#include "postquantiquecoin/blockchain/Difficulty.h"
#include "postquantiquecoin/blockchain/MerkleTree.h"
#include "postquantiquecoin/core/Constants.h"
#include "postquantiquecoin/mining/PQPow.h"
#include <chrono>
namespace pqc {
bool Consensus::HashMeetsCompactTarget(const std::string& hashHex,uint32_t bits){ return Difficulty::CheckProofOfWork(hashHex,bits); }
bool Consensus::ValidateProofOfWork(const BlockHeader& header){ return HashMeetsCompactTarget(header.GetHash(), header.bits); }
bool Consensus::ValidateProofOfWork(const BlockHeader& header,const ChainParams& params){ return Difficulty::CheckProofOfWorkHash(PQPow::ComputePowHash(header,params), header.bits); }
Result<void> Consensus::ValidatePowAlgorithm(const BlockHeader& header,const ChainParams& params){ if(header.powAlgorithmId!=static_cast<uint16_t>(params.powAlgorithm)) return Result<void>::Err("block powAlgorithmId mismatch"); if(params.powAlgorithm==PowAlgorithm::DoubleSha256Legacy){ if(params.networkId==1) return Result<void>::Err("legacy proof-of-work forbidden on mainnet"); if(!params.allowLegacyPow) return Result<void>::Err("legacy proof-of-work disabled"); } return Result<void>::Ok(); }
Result<void> Consensus::ValidateMedianTimePast(const BlockHeader& header,uint64_t medianTimePast){ return header.timestamp>medianTimePast?Result<void>::Ok():Result<void>::Err("timestamp is not greater than median time past"); }
Result<void> Consensus::ValidateTimestamp(uint64_t timestamp){ auto now=static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); if(timestamp>now+constants::MAX_FUTURE_BLOCK_TIME_SECONDS) return Result<void>::Err("block timestamp too far in future"); return Result<void>::Ok(); }
Result<void> Consensus::ValidateHeader(const BlockHeader& header,const ChainParams& params){ auto alg=ValidatePowAlgorithm(header,params); if(alg.IsErr()) return alg; if(!ValidateProofOfWork(header,params)) return Result<void>::Err("insufficient proof of work"); return ValidateTimestamp(header.timestamp); }
Result<void> Consensus::ValidateMerkleRoot(const Block& block){ return block.header.merkleRoot==MerkleTree::ComputeRoot(block.transactions)?Result<void>::Ok():Result<void>::Err("invalid merkle root"); }
Result<void> Consensus::ValidateSubsidy(uint64_t coinbaseAtoms,const ChainParams& params,uint64_t height,uint64_t alreadyMinted,uint64_t fees){ uint64_t subsidy=params.GetBlockSubsidy(height,alreadyMinted); if(UINT64_MAX-subsidy<fees) return Result<void>::Err("reward overflow"); if(coinbaseAtoms>subsidy+fees) return Result<void>::Err("coinbase reward too high"); if(alreadyMinted>params.maxSupplyAtoms || subsidy>params.maxSupplyAtoms-alreadyMinted) return Result<void>::Err("max supply exceeded"); return Result<void>::Ok(); }
Result<void> Consensus::ValidateCoinbase(const Block& block,const ChainParams& params,uint64_t alreadyMinted,uint64_t fees){ if(block.transactions.empty()||!block.transactions[0].IsCoinbase()) return Result<void>::Err("missing coinbase"); uint64_t out=0; for(const auto& o:block.transactions[0].outputs){ if(UINT64_MAX-out<o.amountAtoms) return Result<void>::Err("coinbase overflow"); out+=o.amountAtoms; } return ValidateSubsidy(out,params,block.header.height,alreadyMinted,fees); }
Result<void> Consensus::ValidateTransactions(const Block& block,PQCryptoProvider* provider){ for(size_t i=0;i<block.transactions.size();++i){ const auto& tx=block.transactions[i]; auto basic=tx.ValidateBasic(); if(basic.IsErr() && !(i==0&&tx.IsCoinbase())) return basic; if(i>0 && provider && !tx.VerifySignature(*provider)) return Result<void>::Err("bad transaction signature"); } return Result<void>::Ok(); }
Result<void> Consensus::ValidateBlock(const Block& block,const ChainParams& params,uint64_t alreadyMinted,uint64_t fees,PQCryptoProvider* provider){ auto b=block.ValidateBasic(); if(b.IsErr()) return b; auto h=ValidateHeader(block.header,params); if(h.IsErr()) return h; auto m=ValidateMerkleRoot(block); if(m.IsErr()) return m; auto c=ValidateCoinbase(block,params,alreadyMinted,fees); if(c.IsErr()) return c; return ValidateTransactions(block,provider); }
}
