#include "postquantiquecoin/blockchain/Consensus.h"
#include "postquantiquecoin/blockchain/MerkleTree.h"
#include "postquantiquecoin/core/Constants.h"
#include "postquantiquecoin/core/Hex.h"
#include <chrono>
namespace pqc {
namespace { std::vector<uint8_t> TargetFromCompact(uint32_t bits){ uint32_t exponent=bits>>24; uint32_t mantissa=bits&0x007fffffU; std::vector<uint8_t> target(32,0); if(exponent<=3){ mantissa >>= 8*(3-exponent); target[31]=mantissa&0xff; target[30]=(mantissa>>8)&0xff; target[29]=(mantissa>>16)&0xff; } else { int idx=32-static_cast<int>(exponent); if(idx>=0&&idx<32) target[idx]=static_cast<uint8_t>((mantissa>>16)&0xff); if(idx+1>=0&&idx+1<32) target[idx+1]=static_cast<uint8_t>((mantissa>>8)&0xff); if(idx+2>=0&&idx+2<32) target[idx+2]=static_cast<uint8_t>(mantissa&0xff); } return target; } }
bool Consensus::HashMeetsCompactTarget(const std::string& hashHex,uint32_t bits){ auto hres=Hex::Decode(hashHex); if(hres.IsErr()||hres.Value().size()!=32) return false; auto target=TargetFromCompact(bits); return hres.Value()<=target; }
bool Consensus::ValidateProofOfWork(const BlockHeader& header){ return HashMeetsCompactTarget(header.GetHash(), header.bits); }
Result<void> Consensus::ValidateTimestamp(uint64_t timestamp){ auto now=static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); if(timestamp>now+constants::MAX_FUTURE_BLOCK_TIME_SECONDS) return Result<void>::Err("block timestamp too far in future"); return Result<void>::Ok(); }
Result<void> Consensus::ValidateHeader(const BlockHeader& header,const ChainParams&){ if(!ValidateProofOfWork(header)) return Result<void>::Err("insufficient proof of work"); return ValidateTimestamp(header.timestamp); }
Result<void> Consensus::ValidateMerkleRoot(const Block& block){ return block.header.merkleRoot==MerkleTree::ComputeRoot(block.transactions)?Result<void>::Ok():Result<void>::Err("invalid merkle root"); }
Result<void> Consensus::ValidateSubsidy(uint64_t coinbaseAtoms,const ChainParams& params,uint64_t height,uint64_t alreadyMinted,uint64_t fees){ uint64_t subsidy=params.GetBlockSubsidy(height,alreadyMinted); if(UINT64_MAX-subsidy<fees) return Result<void>::Err("reward overflow"); if(coinbaseAtoms>subsidy+fees) return Result<void>::Err("coinbase reward too high"); if(alreadyMinted+subsidy>params.maxSupplyAtoms) return Result<void>::Err("max supply exceeded"); return Result<void>::Ok(); }
Result<void> Consensus::ValidateCoinbase(const Block& block,const ChainParams& params,uint64_t alreadyMinted,uint64_t fees){ if(block.transactions.empty()||!block.transactions[0].IsCoinbase()) return Result<void>::Err("missing coinbase"); uint64_t out=0; for(const auto& o:block.transactions[0].outputs){ if(UINT64_MAX-out<o.amountAtoms) return Result<void>::Err("coinbase overflow"); out+=o.amountAtoms; } return ValidateSubsidy(out,params,block.header.height,alreadyMinted,fees); }
Result<void> Consensus::ValidateTransactions(const Block& block,PQCryptoProvider* provider){ for(size_t i=0;i<block.transactions.size();++i){ const auto& tx=block.transactions[i]; auto basic=tx.ValidateBasic(); if(basic.IsErr() && !(i==0&&tx.IsCoinbase())) return basic; if(i>0 && provider && !tx.VerifySignature(*provider)) return Result<void>::Err("bad transaction signature"); } return Result<void>::Ok(); }
Result<void> Consensus::ValidateBlock(const Block& block,const ChainParams& params,uint64_t alreadyMinted,uint64_t fees,PQCryptoProvider* provider){ auto b=block.ValidateBasic(); if(b.IsErr()) return b; auto h=ValidateHeader(block.header,params); if(h.IsErr()) return h; auto m=ValidateMerkleRoot(block); if(m.IsErr()) return m; auto c=ValidateCoinbase(block,params,alreadyMinted,fees); if(c.IsErr()) return c; return ValidateTransactions(block,provider); }
}
