#include "postquantiquecoin/blockchain/Mempool.h"
#include "postquantiquecoin/blockchain/ChainValidation.h"
#include "postquantiquecoin/core/Constants.h"
#include <algorithm>
#include <chrono>
namespace pqc {
Result<void> Mempool::AddTransaction(const Transaction& tx,const UTXOSet& utxos,uint64_t height,const ChainParams& params,PQCryptoProvider* crypto){ if(tx.IsCoinbase()) return Result<void>::Err("coinbase not accepted in mempool"); auto b=tx.ValidateBasic(); if(b.IsErr()) return b; std::string id=tx.txid.empty()?tx.ComputeTxId():tx.txid; if(entries_.count(id)) return Result<void>::Err("duplicate mempool transaction"); if(tx.EstimatedSize()>constants::MAX_TRANSACTION_BYTES) return Result<void>::Err("transaction too large"); if(DetectConflicts(tx)) return Result<void>::Err("mempool double spend"); uint64_t inSum=0; for(const auto& in:tx.inputs){ auto u=utxos.GetUTXO(in.previousTxid,in.outputIndex); if(!u) return Result<void>::Err("missing utxo"); if(!u->IsSpendable(height,params.coinbaseMaturity)) return Result<void>::Err("immature coinbase"); if(crypto){ if(u->publicKeyHash==std::array<uint8_t,32>{}) { if(!tx.VerifySignature(*crypto)) return Result<void>::Err("bad signature"); } else { auto auth=ChainValidation::ValidateSpendAuthorization(in,*u,tx,&in-&tx.inputs[0],*crypto,params); if(auth.IsErr()) return auth; } } if(UINT64_MAX-inSum<u->amountAtoms) return Result<void>::Err("input overflow"); inSum+=u->amountAtoms; } uint64_t outSum=tx.GetOutputSum(); if(inSum<outSum) return Result<void>::Err("outputs exceed inputs"); MempoolEntry e; e.tx=tx; e.feeAtoms=inSum-outSum; e.receivedTimestamp=static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count()); e.serializedSize=tx.EstimatedSize(); e.feeRate=e.serializedSize?static_cast<double>(e.feeAtoms)/static_cast<double>(e.serializedSize):0.0; entries_[id]=e; for(const auto& in:tx.inputs) spent_.insert(in.previousTxid+":"+std::to_string(in.outputIndex)); return Result<void>::Ok(); }
void Mempool::RemoveTransaction(const std::string& txid){ auto it=entries_.find(txid); if(it==entries_.end()) return; for(const auto& in:it->second.tx.inputs) spent_.erase(in.previousTxid+":"+std::to_string(in.outputIndex)); entries_.erase(it); }
bool Mempool::HasTransaction(const std::string& txid) const { return entries_.count(txid)!=0; }
std::optional<Transaction> Mempool::GetTransaction(const std::string& txid) const { auto it=entries_.find(txid); if(it==entries_.end()) return std::nullopt; return it->second.tx; }
std::vector<Transaction> Mempool::GetTransactionsForBlock(size_t maxCount,size_t maxBytes) const { std::vector<MempoolEntry> es; for(const auto& kv:entries_) es.push_back(kv.second); std::sort(es.begin(),es.end(),[](const auto&a,const auto&b){ if(a.feeRate==b.feeRate) return a.receivedTimestamp<b.receivedTimestamp; return a.feeRate>b.feeRate; }); std::vector<Transaction> out; size_t bytes=0; for(const auto& e:es){ if(out.size()>=maxCount) break; if(bytes+e.serializedSize>maxBytes) continue; out.push_back(e.tx); bytes+=e.serializedSize; } return out; }
void Mempool::RemoveConfirmedTransactions(const Block& block){ for(const auto& tx:block.transactions) RemoveTransaction(tx.txid.empty()?tx.ComputeTxId():tx.txid); }
void Mempool::Clear(){ entries_.clear(); spent_.clear(); }
size_t Mempool::Size() const { return entries_.size(); }
uint64_t Mempool::GetTotalFeesEstimate() const { uint64_t s=0; for(const auto& kv:entries_) if(UINT64_MAX-s>=kv.second.feeAtoms) s+=kv.second.feeAtoms; return s; }
bool Mempool::DetectConflicts(const Transaction& tx) const { for(const auto& in:tx.inputs) if(spent_.count(in.previousTxid+":"+std::to_string(in.outputIndex))) return true; return false; }
}
