#include "postquantiquecoin/blockchain/Transaction.h"
#include "postquantiquecoin/core/Constants.h"
#include "postquantiquecoin/core/Serialization.h"
#include "postquantiquecoin/crypto/Address.h"
#include "postquantiquecoin/crypto/Hashing.h"
#include <set>
namespace pqc {
bool Transaction::IsCoinbase() const { return inputs.size()==1 && inputs[0].IsCoinbase(); }
std::vector<uint8_t> Transaction::Serialize(bool includeSignature) const { Serializer s; s.U32(version); s.U64(timestamp); s.U64(locktime); s.String(signatureAlgorithm); s.U64(inputs.size()); for(const auto& in:inputs){ s.String(in.previousTxid); s.U32(in.outputIndex); if(includeSignature) s.Bytes(in.unlockingSignature); else s.Bytes({}); s.Bytes(in.publicKey); } s.U64(outputs.size()); for(const auto& out:outputs){ s.U64(out.amountAtoms); s.String(out.address); s.String(out.lockingScriptType); } if(includeSignature){ s.Bytes(publicKey); s.Bytes(signature); } return s.Data(); }
Result<Transaction> Transaction::Deserialize(const std::vector<uint8_t>& data){ Deserializer d(data); Transaction tx; auto v=d.U32(); if(v.IsErr()) return Result<Transaction>::Err(v.Error()); tx.version=v.Value(); auto ts=d.U64(); if(ts.IsErr()) return Result<Transaction>::Err(ts.Error()); tx.timestamp=ts.Value(); auto lt=d.U64(); if(lt.IsErr()) return Result<Transaction>::Err(lt.Error()); tx.locktime=lt.Value(); auto alg=d.String(); if(alg.IsErr()) return Result<Transaction>::Err(alg.Error()); tx.signatureAlgorithm=alg.Value(); auto ni=d.U64(); if(ni.IsErr()) return Result<Transaction>::Err(ni.Error()); if(ni.Value()>constants::MAX_TX_INPUTS) return Result<Transaction>::Err("too many inputs"); for(uint64_t i=0;i<ni.Value();++i){ TxInput in; auto p=d.String(); if(p.IsErr()) return Result<Transaction>::Err(p.Error()); in.previousTxid=p.Value(); auto oi=d.U32(); if(oi.IsErr()) return Result<Transaction>::Err(oi.Error()); in.outputIndex=oi.Value(); auto us=d.Bytes(); if(us.IsErr()) return Result<Transaction>::Err(us.Error()); in.unlockingSignature=us.Value(); auto pk=d.Bytes(); if(pk.IsErr()) return Result<Transaction>::Err(pk.Error()); in.publicKey=pk.Value(); tx.inputs.push_back(in); } auto no=d.U64(); if(no.IsErr()) return Result<Transaction>::Err(no.Error()); if(no.Value()>constants::MAX_TX_OUTPUTS) return Result<Transaction>::Err("too many outputs"); for(uint64_t i=0;i<no.Value();++i){ TxOutput out; auto amt=d.U64(); if(amt.IsErr()) return Result<Transaction>::Err(amt.Error()); out.amountAtoms=amt.Value(); auto a=d.String(); if(a.IsErr()) return Result<Transaction>::Err(a.Error()); out.address=a.Value(); auto l=d.String(); if(l.IsErr()) return Result<Transaction>::Err(l.Error()); out.lockingScriptType=l.Value(); tx.outputs.push_back(out); } auto pk=d.Bytes(); if(pk.IsErr()) return Result<Transaction>::Err(pk.Error()); tx.publicKey=pk.Value(); auto sig=d.Bytes(); if(sig.IsErr()) return Result<Transaction>::Err(sig.Error()); tx.signature=sig.Value(); tx.txid=tx.ComputeTxId(); return Result<Transaction>::Ok(tx); }
std::vector<uint8_t> Transaction::GetSigningDigest() const { std::vector<uint8_t> d(constants::TX_SIGN_DOMAIN, constants::TX_SIGN_DOMAIN + std::char_traits<char>::length(constants::TX_SIGN_DOMAIN)); auto body=Serialize(false); d.insert(d.end(),body.begin(),body.end()); auto h=Hashing::Sha3_256(d); return {h.begin(),h.end()}; }
std::string Transaction::ComputeTxId() const { return Hashing::Sha3_256Hex(Serialize(true)); }
uint64_t Transaction::GetOutputSum() const { uint64_t sum=0; for(const auto& out:outputs){ if(UINT64_MAX-sum<out.amountAtoms) return UINT64_MAX; sum+=out.amountAtoms; } return sum; }
std::vector<std::pair<std::string,uint32_t>> Transaction::GetInputOutpoints() const { std::vector<std::pair<std::string,uint32_t>> v; for(const auto& in:inputs) v.push_back({in.previousTxid,in.outputIndex}); return v; }
size_t Transaction::EstimatedSize() const { return Serialize(true).size(); }
Result<void> Transaction::ValidateBasic() const { if(inputs.empty()) return Result<void>::Err("transaction has no inputs"); if(outputs.empty()) return Result<void>::Err("transaction has no outputs"); if(inputs.size()>constants::MAX_TX_INPUTS || outputs.size()>constants::MAX_TX_OUTPUTS) return Result<void>::Err("transaction vector limit exceeded"); if(Serialize(true).size()>constants::MAX_TRANSACTION_BYTES) return Result<void>::Err("transaction too large"); std::set<std::pair<std::string,uint32_t>> seen; for(const auto& in:inputs){ if(!seen.insert({in.previousTxid,in.outputIndex}).second) return Result<void>::Err("duplicate input"); } uint64_t sum=0; for(const auto& out:outputs){ if(out.amountAtoms==0) return Result<void>::Err("zero output"); if(out.amountAtoms>constants::MAX_SUPPLY_ATOMS || UINT64_MAX-sum<out.amountAtoms) return Result<void>::Err("output overflow"); if(!Address::Validate(out.address)) return Result<void>::Err("invalid address"); sum+=out.amountAtoms; } if(!IsCoinbase()){ bool hasGlobal=!publicKey.empty() && !signature.empty(); bool hasInputs=true; for(const auto& in:inputs){ if(in.publicKey.empty() || in.unlockingSignature.empty()) hasInputs=false; } if(!hasGlobal && !hasInputs) return Result<void>::Err("missing signature"); } return Result<void>::Ok(); }
void Transaction::Sign(PQCryptoProvider& provider,const std::vector<uint8_t>& privateKey,const std::vector<uint8_t>& pubKey){ publicKey=pubKey; signature=provider.Sign(privateKey,GetSigningDigest()); for(auto& in:inputs){ if(!in.IsCoinbase()){ in.publicKey=pubKey; in.unlockingSignature=signature; } } txid=ComputeTxId(); }
bool Transaction::VerifySignature(PQCryptoProvider& provider) const { if(IsCoinbase()) return true; if(outputs.empty()) return false; auto digest=GetSigningDigest(); bool hasPerInput=true; for(const auto& in:inputs){ if(in.IsCoinbase()) continue; if(in.publicKey.empty()||in.unlockingSignature.empty()||!provider.Verify(in.publicKey,digest,in.unlockingSignature)) hasPerInput=false; } if(hasPerInput) return true; if(publicKey.empty()||signature.empty()) return false; return provider.Verify(publicKey, digest, signature); }
bool Transaction::Verify(PQCryptoProvider& provider) const { return VerifySignature(provider); }
}
